# Generated by Django 3.1.7 on 2022-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/%Y/%m/%d', verbose_name='プロフィール写真'),
        ),
    ]
