version: "3"
services:
  backend:
    build: ./backend
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    environment:
      - DEBUG=1
    depends_on:
      - db

volumes:
  pgdata:
