# Generated by Django 3.1.7 on 2023-01-17 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0002_case_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='case_member', to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
    ]
