# Generated by Django 3.1.7 on 2022-12-22 08:34

import article.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='カテゴリー')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, validators=[article.models.check_event_name], verbose_name='スラッグ')),
                ('body', models.TextField(blank=True, max_length=1500, null=True, verbose_name='説明')),
                ('release', models.BooleanField(default=True, verbose_name='公開する')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True, verbose_name='記事タイトル')),
                ('thumbnail', models.ImageField(null=True, upload_to='article/%Y/%m/%d', verbose_name='サムネイル')),
                ('url1', models.URLField(blank=True, null=True, verbose_name='参考ページ1')),
                ('url2', models.URLField(blank=True, null=True, verbose_name='参考ページ2')),
                ('url3', models.URLField(blank=True, null=True, verbose_name='参考ページ3')),
                ('body', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('release', models.BooleanField(default=True, verbose_name='公開する')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('category', models.ManyToManyField(blank=True, null=True, related_name='category', to='article.Category', verbose_name='カテゴリ')),
            ],
        ),
    ]
