# Generated by Django 3.1.7 on 2023-01-04 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20221222_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='お気に入りに登録する')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='article.article', verbose_name='記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='お気に入りしたユーザー')),
            ],
        ),
    ]
